# Generated by Django 2.2 on 2019-07-31 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('address', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='unknown', max_length=10)),
                ('category', models.CharField(choices=[('Produce', 'Produce'), ('Cat Products', 'Cat Products'), ('Apparel', 'Apparel'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='listings.Listing')),
                ('status', models.BooleanField()),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='listings.Listing')),
                ('winning_bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winning_bid', to='listings.Listing')),
            ],
        ),
    ]
