# Generated by Django 2.2.3 on 2019-07-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
