# Generated by Django 2.2.3 on 2019-07-26 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190720_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='listings.Listing')),
                ('status', models.BooleanField()),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='listings.Listing')),
                ('winning_bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winning_bid', to='listings.Listing')),
            ],
        ),
    ]
