# Generated by Django 2.2 on 2019-07-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_transaction'),
        ('listings', '0002_listing_category'),
    ]

    operations = [
    ]
