# Generated by Django 2.2 on 2019-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_merge_20190728_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Produce', 'Produce'), ('Cat Products', 'Cat Products'), ('Apparel', 'Apparel'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=100),
        ),
    ]
